### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ssoonmi** [ConleyPotter/Middle#1]
- [x] the dates for your MVP's should be the date you intend to complete each of them by

### Auth
- [x] remove chirps from third bullet point

### Articles
- [x] Users should be able to view other's articles

### Follows and Feed
- [x] first bullet point is incomplete

### Claps
- [x] I think you should put claps before Follows and Feed because it's an easier MVP to get done

### Search
- [x] Bonuses should come after the Production README

**Comment by ConleyPotter** [comment]
Thanks for the thoughtful issue, Soon-Mi! I have made the appropriate changes.
