### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [ConleyPotter/Middle#2]
### `users`
- [x] `username` should have `unique` in the details column
- [x] `email` should have an index with `unique: true`

### `articles`
- [x] should also have a `title`

### `comments`
- [x] should have a body

### `claps`
- [x] should not have a unique index on `user_id`

### `follows`
- [x] should not have a unique index on `user_id`

**Comment by ConleyPotter** [comment]
Thanks Soon-Mi! All fixed up!

**Comment by ssoonmi** [comment]
I think you forgot to fix the users table.

**Comment by ConleyPotter** [comment]
You're right, I thought I fixed that too, my bad.
