### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [ConleyPotter/Middle#3]
### articles
- [x] an article should hold a reference to its comments as commentIds

### claps
- [x] claps do not have to be in the state because all it holds are foreign keys. Instead, you should have a key on an article of clapUserIds that will point to an array of user ids who have clapped the article

### follows
- [x] follows do not have to be in the state. see my comment on claps. Instead you should have keys on the users slice of state like followerIds and followeeIds

Nice Sample State!

**Comment by ConleyPotter** [comment]
Thanks, Soon-Mi! I made the appropriate changes.

**Comment by ssoonmi** [comment]
### `comments`
- [ ] should have a reference to its article using `article_id`

**Comment by ConleyPotter** [comment]
Got it, thanks Soon-Mi!
