### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by ssoonmi** [ConleyPotter/Middle#4]
### `comments`
- [x] need to nest comments under articles for POST route

great job on the backend routes!

**Comment by ConleyPotter** [comment]
Hey Soon-Mi, should all the comment routes be nested under articles? Or just the comment POST route?

**Comment by ssoonmi** [comment]
Only the GET and POST requests should be nested. You can edit or delete a comment using just the id. But if you want to get a bunch of comments or POST a comment without an id yet, we need to nest the routes.
