### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ssoonmi** [ConleyPotter/Middle#6]
- [x] don't need become a member page because it requires way more styling than necessary. Having the login and signup form modals should be good enough

### NavBar
- [x] the navbar should be taller
- [x] the text should be smaller and maybe lighter font-weight
- [x] should be more padding around the GetStarted button
- [x] Medium's navbar links have a slight hover effect that changes the color slightly

### Login / Signup Forms
- [x] the (x) button to close the modal should be at the very top right corner of the form
- [x] the modal background is supposed to be whiter
- [x] should be a space between `No Account?` and `Create One`
- [x] the `Log In` button to submit should have the text centered
- [x] don't need the terms of service and private policy since you don't have them
- [x] to log in, you should be able to log in with a username or email, requiring both
- [x] when refreshing after logging in/signing up, it doesn't save my session
- [x] should have a demo log in feature
- [x] on the sign up form, the `Already have an account? Log In` feature doesn't work
- [x] you should render errors on the form if there is something wrong with submitting to the backend. You should only close the modal if the signup/login is successful

### Logout / Profile Dropdown
- [x] when a user is signed in, you should render the profile dropdown menu with the logout button as a menu item

**Comment by ConleyPotter** [comment]
All fixed up on the user_auth branch! Should I deploy that branch to heroku?
